---

sudo: required
languages: ruby
services:
  - docker

script:
  - echo "VOLUME /var/log" >> Dockerfile
  - docker build -t alpine-peervpn .
  - mkdir /tmp/log
  - docker run -v /tmp/log:/var/log -d --name=test -p 7000:7000/udp --privileged alpine-peervpn
  - sleep 5
  - cat /tmp/log/peervpn.log
